### ISSUE TITLE
#111 - Notifications not showing after friends were made

### ISSUE THREAD

**Issue by aidataguy** [thedesignable/selfiewise#3]
Notifications were not showing after friend was added.

--- Was not working previously.. fixed now --- replaced Noty with Sweeetlearts V2. Updated Vue to Vue 2. 

Precision file system added. 

![screenshot from 2017-10-27 17-53-22](https://user-images.githubusercontent.com/10688315/32103909-fbd7fdd6-bb3f-11e7-8125-cfa080bce6ae.png)

**Comment by thedesignable** [comment]
Issue fixed in 428cbf2

**Comment by aidataguy** [comment]
Issue fixed in 428cbf2
